apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: greeter-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: greeter-api
  template:
    metadata:
      labels:
        name: greeter-api
    spec:
      containers:
        - name: discovery
          command: [
		"/greeter-api",
		"--server_address=0.0.0.0:9090",
		"--broker_address=0.0.0.0:10001"
	  ]
          image: microhq/greeter-api:kubernetes
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: api-port
